### ISSUE TITLE
Need a unique species list with abundances for sites, site_types, campaigns and campaign_types. 

### ISSUE THREAD

**Issue by glaroc** [ReseauBiodiversiteQuebec/Coleo_DB#57]

**Comment by vincent-beauregard-ielab** [comment]
Function created `api.taxa_abundance(column_name)` 
Returns a table for with the abundance obtained from `obs_species` for each taxon, grouped by the column name specified as parameter. The column name accepted can be any of : `site_id`, `site_type`, `campaign_id`, `campaign_type`, `cell_id`, `cell_code`.

**Notes**:
* Based only on `obs_species`
* To make it work, I updated `obs_species` to set value = 1 where `variable` = `présence` instead of `NULL`
* Many variables are not comparable (abundance, presence, area) and precautions most be done to make `top` list of observed species for a site for example.
* Returns all observed taxons as wrote in `obs_species` table that may be of any rank. For example, the most abundant taxa observed for campaign_type `insectes_sol` is `insecta`.

**Comment by vincent-beauregard-ielab** [comment]
Tu peux fermer la issue si ça correspond bien à tes attentes !
